<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Payroll Slip</title>
    <style>
        body {
            font-family: 'Arial, sans-serif';
            margin: 20px;
        }

        h1 {
            text-align: center;
            color: #333;
        }

        .payroll-details {
            margin-top: 20px;
            border: 1px solid #ccc;
            padding: 15px;
        }

        .payroll-details p {
            margin: 8px 0;
        }

        .footer {
            margin-top: 20px;
            text-align: center;
            color: #666;
        }
    </style>
</head>
<body>
    <h1>Payroll Slip</h1>
    <div class="">
        <p><em>Date: {{ now() }}</em></p>
    </div>
    <div class="">
        <p><em>Generated By: {{ session('user_name')}}</em></p>
    </div>
    <div class="payroll-details">
        <p><strong>Date:</strong> {{ $payroll->created_at->format('Y-m-d') }}</p>
        <p><strong>Employee ID:</strong> {{ $payroll->EmployeeID }}</p>
        <p><strong>Employee Name:</strong> {{ $payroll->EmployeeName }}</p>
        <p><strong>Basic Pay:</strong> Php{{ $payroll->RPH }}</p>
        <p><strong>Days:</strong> {{ $payroll->TotalDays }}</p>
        <p><strong>Basic Salary:</strong> Php{{ $payroll->Salary }}</p>
        @if($payroll->Overtime > 0)
        <p><strong>------------------------------------------------------------------------------------------------------------------------</strong></p>
        <p><strong>Overtime Rate:</strong> Php{{ $payroll->OTrate }}</p>
        <p><strong>Total Overtime Hours:</strong> {{ $payroll->Overtime }}</p>
        <p><strong>Total Overtime Salary:</strong> {{ $payroll->OTSalary }}</p>
        
        @endif
        <p><strong>------------------------------------------------------------------------------------------------------------------------</strong></p>
        <p><strong>GrossIncome:</strong> Php{{ $payroll->GrossIncome }}</p>
        <p><strong>------------------------------------------------------------------------------------------------------------------------</strong></p>
        <p><strong>Less Deductions:</strong></p><br>
        <p><strong>TAX:</strong> Php{{ $payroll->Tax }}</p>
        <p><strong>SSS:</strong> Php{{ $payroll->SSS }}</p>
        <p><strong>PHILHEALTH:</strong> Php{{ $payroll->PHILHEALTH }}</p>
        <p><strong>PAGIBIG:</strong> Php{{ $payroll->PAGIBIG }}</p>
        <p><strong>-------------------------------------------------------------------------------------------------------------------------</strong></p>
        <p><strong>Total Deduction:</strong> Php{{ $payroll->TotalDeduction }}</p>
        <p><strong>NetIncome:</strong> Php{{ $payroll->NetIncome }}</p>
    </div>
    
</body>
</html>
